services:
  wwjcar-frontend:
    image: nginx:alpine
    container_name: wwjcar-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - /home/ubuntu/infra/projects/wwjcar/frontend/dist:/usr/share/nginx/html:ro
      - /home/ubuntu/infra/projects/wwjcar/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:172.18.0.1"
    networks:
      - manager-net

networks:
  manager-net:
    external: true
